### ISSUE TITLE
Max amp output 4x usb hub RPI

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [owncloud-archive/ubuntu-snap#12]
I've done some research on wifi dongle's, the large one's pull up to 0.6 mA total with board (idle).
Now the small one's I don't know yet but I assume a bit less. I think its best to set this value at max, since it only uses it when needed. And without the (wifi) network the PI does nothing.

Recommended RPI PSU's deliver 2 mA
###### 

USB Power
###### 

;max_usb_current
;    When set to 1, change the output current limit (for all 4 USB
;    ports combined) from 600mA to double that, 1200mA.
;
;    This option is not available for Model A/B boards.
;
;    Default 0.
;
max_usb_current=1
###### 

Also, WD ships the kit with a powered hub as I understand so this option would prevent possible performance issue's. I heard various cases where a Raspberry would reboot at insufficiënt power.

**Comment by oparoz** [comment]
@ezraholm50, please clone this in https://github.com/owncloud/pi-image/issues as those settings cannot be tuned from within an app snap.

**Comment by WaaromZoMoeilijk** [comment]
@oparoz second thought, I think its wiser to leave it, did some more research and the dongle will work but the performance will lack. I think its better to have all the juice go to the PI instead. I'd like to hear more oppinions on this matter. I will also try different dongle's next few weeks to find out if it really matters. I have a large on dualband and a small one!

**Comment by oparoz** [comment]
OK, but still an issue for pi-image, so I'm closing this and you can re-open it there if you think it's something which needs to be explored.
