### ISSUE TITLE
10% performance gain - Lower number of interrupts when USB is idle - dwc_otg.fiq_fix_enable=1 

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [owncloud-archive/ubuntu-snap#13]
When this `dwc_otg.fiq_fix_enable=1` is added to cmdline.txt it should boost performance.

`Lowers the number of interrupts when USB is idle, gains about 10% performance on the ARM side`

http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=7866&start=75

**Comment by oparoz** [comment]
@ezraholm50, please clone this in https://github.com/owncloud/pi-image/issues as those settings cannot be tuned from within an app snap.
