### ISSUE TITLE
Power supply

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [owncloud-archive/ubuntu-snap#16]
@jospoortvliet Today during our meet me, oparoz and kyrofa where discussing our recent error logs related to possible power supply failure.

I heard that the test kit of WD supplies only 2 amps of power. By default the PI delivers 0.6 mA divided over 4 usb ports. Now you can set that to be 1.2 mA over the 4. 

When we overclock we need all the juice we can get, not only that even when not overclocking RPI devs recommend a 2 amp PSU at 5V.

My test build had an SSD which pulls 1.5A (thought it was much less) with no powered hub, I had the same issues as @oparoz (running a test kit, HD with moving parts) you get the point.

So our suggestion is to contact WD, for sure before the new batch of kits comes out, to review their PSU/PHUB. Suggest making it 2A, 5V + needs for HD

Yesterday posted #12

**Comment by oparoz** [comment]
I've tested with 0.75A for the PI and 2A for the HD and while it seemed more stable at first, it died again in a tragic RAM asphyxiation accident, so we'll have to figure out how to make MySQL stop being so murderous, although systemd was the top CPU eater, so maybe he's the one to blame (I don't know systemd).

**Comment by oparoz** [comment]
Tried with 2 x 2A, same result. I think we can rule out the power supply.

**Comment by WaaromZoMoeilijk** [comment]
Voltage at both?

**Comment by oparoz** [comment]
You're not supposed to touch the voltage, so it's 5V, but probably oscillates between 4.8 and 5.2

**Comment by WaaromZoMoeilijk** [comment]
I know but thats indeed what i wanted to know, shouldnt drop below 4.8 then its good.
Got it overclocked? Could be more stable at over voltage maybe, will investigate. Im going to check if my build also has those problems with the client.

**Comment by oparoz** [comment]
> Im going to check if my build also has those problems with the client.

Yep, that would be useful.

I think the lack of swap is what's killing it. It can't perform some essentials tasks because there is no memory left

**Comment by WaaromZoMoeilijk** [comment]
I'll make a swapfile of 2GB at swappiness 5, will report back.

**Comment by WaaromZoMoeilijk** [comment]
@oparoz my BerryBoot build works very well. And fast, visit the wiki of my repo for info whats on it.

No problem with the sync client, no timeouts, goes quite fast.

1 sync client active with https://www.techandme.se/stress-test/ syncing only spikes 4x cpu to 75% but average on 40%

Memory usage not more then 35%, swap not used, 2GB file, swappiness 10

WEBGUI OC is slower when syncing but works. Also no errors in the log file.

Overclocked at dynamic max/min:
Arm 1000/700
core 500/250
sdram 500/400
overvolt 1.35/1.2
sdram overvolt 1.35

**Comment by oparoz** [comment]
I think we can disregard power supply issues as other versions of the snap don't experience these stability issues.

**Comment by jospoortvliet** [comment]
Yup. For a final version to be shipped, WD will make sure it's all tested and can run with multiple drives at max performance.

**Comment by oparoz** [comment]
Thanks!
