### ISSUE TITLE
libssl-dev missing from list of Apache dependencies

### ISSUE THREAD

**Issue by oparoz** [owncloud-archive/ubuntu-snap#17]
When snapcrafting the ownCloud snap in a clean environment, Apache failed during the build step, complaining about some missing OpenSSL headers.

The fix is to modify the Apache python plugin to include:
- libssl-dev
- libssl1.0.0
- zlib1g-dev

@kyrofa

**Comment by kyrofa** [comment]
This issue probably belongs [upstream](https://github.com/kyrofa/owncloud-snap/issues), no?

**Comment by oparoz** [comment]
:facepalm: I thought I was upstream...
