### ISSUE TITLE
Findings snappy core img

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [owncloud-archive/ubuntu-snap#9]
Don't really know where to put all the seperate findings so ill state them here.
Have not had a great deal of time to spend testing.
**Setup: 32 GB SSD Writable / SD card class 4 Boot**

@kyrofa @oparoz As for the resize, it checked it at boot and said there was more then 10% free space so it did the resize, properly!

-Overclocking, the overclock settings I had from my project don't really work, unable to boot. So I'm just figuring out what settings do work.

-Booting/shutting down seems a bit slow in comparison to the image I used, probably is because of the overclocking that isn't setup on the snappy kit here just yet. I'll do some test runs with boot time to login. @kyrofa I still don't really know what image I got, snappy core with apt without snappy I guess.

-Overall performance is just fine and amazed me, and redis (or something similar) still needs to be installed.
*_---edit, with a few apps enabled only out of the box apps, the performance is kind of ok... *_

-Default enable cron, most unknown users would not know what the heck thats about.

-Maybe install smbclient snap? To mount external shares.

-Https enabled by default, snake oil stuff / lets encrypt

**Comment by oparoz** [comment]
> Im running it on a 32 gb SSD i had lying around covered in dust.

You've not connected a hard drive? If that's the case, that may explain why things are working as expected on your setup.

**Comment by WaaromZoMoeilijk** [comment]
@oparoz  Nah didn't have any 2.5 inch hdds around anymore just this one 2.5 inch ssd, gives some performance gains ofcourse yes...

Are you running it purely of the SDCARD?

Damn, i really need to get to know this snap stuff. Can't even go into .htaccess to up the upload limit...
So i can't really try to upload a large folder... please help, google-ing my ass of right now.

**Comment by oparoz** [comment]
> Are you running it purely of the SDCARD?

No, the kit comes with a USB hard drive and that's where the data, config and apps folder reside.

> Damn, i really need to get to know this snap stuff. Can't even go into .htaccess to up the upload limit...
> So i can't really try to upload a large folder... please help, google-ing my ass of right now.

It's a totally different system. You have very limited access.
Using the sync client, you shouldn't have any issues uploading lots of files and I was able to send files larger than 2MB, thanks to chunking.

**Comment by kyrofa** [comment]
> Can't even go into .htaccess to up the upload limit

Nope, that's read-only. However, if we agree on a good upload limit we can set it in the snap for everyone.

**Comment by WaaromZoMoeilijk** [comment]
@oparoz yeah what I thought, there is quite a difference between hd and ssd... Would be awsome if WD would go for SSD's
- I now setup the sync client to do some syncing will test now.
- @kyrofa maybe max 2 GB? Or would that break functionality of stuff ? Think we should test it bit by bit starting from 256mb, 512mb so on, no?

**Comment by oparoz** [comment]
> @kyrofa maybe max 2 GB? Or would that break functionality of stuff ? Think we should test it bit by bit starting from 256mb, 512mb so on, no?

2GB is what people want. I'm wondering if the 1GB RAM limit is going to be a problem though?

**Comment by oparoz** [comment]
And @ezraholm50 I misread your statement earlier. I thought you were only using a 32GB **SD** card. If you're using the writable image, then you should run into the same issues I am.

**Comment by WaaromZoMoeilijk** [comment]
@oparoz Indeed I am using writable and boot images on an Solid State Drive and SDCARD
after about 250mb timeout and everyting freezes. Feels like i ddos'sed my pi... cant do anything right now. 

Edit: and its back, max transfer over laptop wifi to ethernet PI 6 mb/sec
Edit: 2nd freeze at around 500 mb

**Comment by oparoz** [comment]
Thanks for confirming @ezraholm50 :)

**Comment by kyrofa** [comment]
> 2GB is what people want. I'm wondering if the 1GB RAM limit is going to be a problem though?

Great question, I guess it depends on how the uploads are written (e.g. into a cache directory or into tmpfs somewhere).

**Comment by oparoz** [comment]
Speaking of RAM, I've noticed that there wasn't any SWAP available. Is that a limitation of snaps because you don't want a snap to access content from other snaps?

**Comment by kyrofa** [comment]
> Speaking of RAM, I've noticed that there wasn't any SWAP available. Is that a limitation of snaps because you don't want to access content from other snaps?

I'm not sure about the security aspect of things, but I'd say that swap on the HD would be terribly slow and swap on the SD would eat it alive. I'm not sure there's a great way forward, there.

**Comment by oparoz** [comment]
You're right, it's probably best to force the use of the hard drive when we need to instead of playing Russian roulette by putting everything in RAM.

**Comment by WaaromZoMoeilijk** [comment]
We could try a swapfile/partition? I only noticed gains on my project using it.

4 months testing different setups with 4 sdcards resulted in 1 Killed in action and 3 still work fine
Also testing with swap on the HD (SSD in my case) works better then no swap.

Also I noticed that there where apps in the appstore on the snappy OC build that are not yet OC 9.0 ready yet (at least not on my production server 9.0). Which also gave some dependency errors. Any ideas?

@oparoz @kyrofa @enoch85 @jospoortvliet IRC channel/teamspeak server dedicated to this dev/testing?

**Comment by WaaromZoMoeilijk** [comment]
Well I'll be damned, after nearly an hour I was able to access OC again, trying to enable the app logreader to post the outcome, it froze again. This is a real show stopper until this is fixed.

Where can I find the logs in ssh?

**Comment by oparoz** [comment]
https://github.com/owncloud/pi-image/wiki/Getting-started

**Comment by jospoortvliet** [comment]
@oparoz thanks for that wiki page, that helps a lot ;-)

with regards to a place where to discuss this, #snappy is very busy, so is #owncloud-dev - maybe #techandme then ;-)

I vote for having a swapfile on the HD and using swappiness=5 in sysconfig to simply tell the kernel to only use the swap in dire circumstances. Not 0, we want it to use the swap with data that's barely ever used, 5 seems a good middle ground. (40 is default, I think, or 60 maybe)

@kyrofa where/how do I set stuff like that? A script that makes some adjustments? Similar questions about settings from https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/performance_tuning/webserver_tips.html#apache-tuning

**Comment by WaaromZoMoeilijk** [comment]
@jospoortvliet #techandme IRC it is!

**Comment by oparoz** [comment]
Should we close this now that we have a better idea of how it works and several issues tracking progress on those various elements?

**Comment by jospoortvliet** [comment]
I think so.
